name: Generate Snake
on:
  push:
    branches:
      - main # Ou 'master'
  # Removemos schedule e workflow_dispatch
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: Manuel-Gon
          outputs: |
            dist/snake.svg?palette=github-dark&background=black
            
      - name: Push Snake Animation
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generated Snake Animation"
          add: "dist/snake.svg"
